plugins {
	id 'maven-publish'
}

ext {
	set("springBootVersion", "3.4.5")
}

dependencies {
	implementation project(":project:sprint_17:task_163_java_modules:core_api")
	implementation project(":project:sprint_17:task_163_java_modules:core_domain")
	implementation project(":project:sprint_17:task_163_java_modules:core_validations")
	implementation project(":project:sprint_17:task_163_java_modules:core_underwriting")


	implementation("org.springframework.boot:spring-boot-starter-data-jpa:$springBootVersion")

	compileOnly('org.projectlombok:lombok:1.18.32')
	annotationProcessor('org.projectlombok:lombok:1.18.32')

	testCompileOnly('org.projectlombok:lombok:1.18.32')
	testAnnotationProcessor('org.projectlombok:lombok:1.18.32')

	testImplementation("org.springframework.boot:spring-boot-starter-test:$springBootVersion")

	test {
		useJUnitPlatform()
	}

}

jar {
	enabled = true
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			// Identify the artifact
			artifact jar  // This refers to the Spring Boot's bootJar task

			// Project coordinates
			groupId = 'org.javaguru'
			artifactId = 'insurance-calculator-core-services'
			version = '1.0.0'

			// Add other metadata as needed
			pom {
				name = 'Insurance Calculator Core Services'
				description = 'Core Service Module'
				licenses {
					license {
						name = 'The Apache License, Version 2.0'
						url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
					}
				}
			}
		}
	}

	// Configure the repository location (local Maven repository)
	repositories {
		mavenLocal()
	}
}
