ext {
	set("springBootVersion", "3.4.5")
}

dependencies {

	implementation("org.springframework.boot:spring-boot-starter-web:$springBootVersion")
	implementation('com.fasterxml.jackson.core:jackson-core:2.14.2')

	testImplementation("org.springframework.boot:spring-boot-starter-test:$springBootVersion")

	test {
		useJUnitPlatform()
	}

	compileOnly('org.projectlombok:lombok:1.18.32')
	annotationProcessor('org.projectlombok:lombok:1.18.32')

	testCompileOnly('org.projectlombok:lombok:1.18.32')
	testAnnotationProcessor('org.projectlombok:lombok:1.18.32')

}