plugins {
	id 'org.springframework.boot' version "3.2.5"
	id 'maven-publish'
}

ext {
	set("springBootVersion", "3.4.5")
}

dependencies {
	implementation project(":project:sprint_17:task_163_java_modules:core_api")
	implementation project(":project:sprint_17:task_163_java_modules:core_services")

	implementation project(":project:sprint_17:task_163_java_modules:adapter_dto")
	implementation project(":project:sprint_17:task_163_java_modules:adapter_rest")
	implementation project(":project:sprint_17:task_163_java_modules:adapter_web")

	implementation('mysql:mysql-connector-java:8.0.33')
	implementation ('org.liquibase:liquibase-core:4.27.0')
	implementation('com.h2database:h2:2.2.224')

	implementation("org.springframework.boot:spring-boot-starter-web:$springBootVersion")

	testImplementation("org.springframework.boot:spring-boot-starter-test:$springBootVersion")

	testImplementation('uk.org.webcompere:model-assert:1.0.0')

	test {
		useJUnitPlatform()
	}

}

jar {
	enabled = false
}

bootJar {
	enabled = true
	archiveBaseName = 'insurance-calculator'
	archiveVersion = '1.0.2'
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			// Identify the artifact
			artifact bootJar  // This refers to the Spring Boot's bootJar task

			// Project coordinates
			groupId = 'org.javaguru'
			artifactId = 'insurance-calculator-application'
			version = '1.0.0'

			// Add other metadata as needed
			pom {
				name = 'Insurance Calculator Application'
				description = 'Application to calculate travel insurance premium'
				licenses {
					license {
						name = 'The Apache License, Version 2.0'
						url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
					}
				}
			}
		}
	}

	// Configure the repository location (local Maven repository)
	repositories {
		mavenLocal()
	}
}
